### ISSUE TITLE
Under the concurrent is very unsafe

### ISSUE THREAD

**Issue by barnettZQG** [StabbyCutyou/buffstreams#21]
Under the concurrent is very unsafe
```
panic: runtime error: slice bounds out of range

goroutine 19 [running]:
panic(0x104640, 0xc42000c130)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/barnettZQG/buffstreams.(*TCPConn).Read(0xc4200be060, 0xc4201d9000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/Users/qingguo/gopath/src/github.com/barnettZQG/buffstreams/tcpconn.go:214 +0x14e
github.com/barnettZQG/buffstreams.(*TCPListener).readLoop(0xc42007a510, 0xc4200be060)
	/Users/qingguo/gopath/src/github.com/barnettZQG/buffstreams/tcplistener.go:169 +0x148
created by github.com/barnettZQG/buffstreams.(*TCPListener).blockListen
	/Users/qingguo/gopath/src/github.com/barnettZQG/buffstreams/tcplistener.go:100 +0xa2
exit status 2
```

**Comment by StabbyCutyou** [comment]
Thanks for the bug report, sorry I didn't see it until now.

I'll look into this over the weekend and get back to you.

**Comment by StabbyCutyou** [comment]
Can you provide any sample code to reproduce? And can you reproduce it on my copy of buffstreams, not just your fork? I see you've made some changes, and I want to isolate if it's an issue on my end, or in changes that you've made.

**Comment by StabbyCutyou** [comment]
Closing due to lack of activity
